pool:
   vmImage: 'windows-latest'
 
steps:
- script: pip install -r requirements.txt
  displayName: 'installing dependencies'
   
- script: python setup.py bdist_msi
  displayName: 'installing exe'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
   
   
     
